# Generated by Django 5.1.4 on 2026-06-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
