# Generated by Django 5.1.4 on 2026-08-10 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='staff.staff')),
            ],
            options={
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['staff'], name='staff_staff_staff_i_dc2358_idx')],
            },
        ),
    ]
