# Generated by Django 5.1.4 on 2026-06-09 13:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('service_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('address', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('service_date', models.DateField()),
                ('service_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('skip', 'Skip'), ('not_interested', 'Not Interested')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('frequency', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannually', 'Semi-Annually'), ('annually', 'Annually')], max_length=20, null=True)),
                ('ghl_contact_id', models.TextField(blank=True, null=True)),
                ('service_type', models.TextField(default='installation')),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('call_status', models.TextField(default='not_called')),
                ('calls_made', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service_date', 'service_time'],
                'indexes': [models.Index(fields=['service_date'], name='jobs_job_service_3f039e_idx'), models.Index(fields=['ghl_contact_id'], name='jobs_job_ghl_con_e9ed33_idx'), models.Index(fields=['status'], name='jobs_job_status_7d017a_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('service_date', models.DateField()),
                ('service_time', models.TimeField(blank=True, null=True)),
                ('service_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('staff_ids', models.JSONField(default=list)),
                ('product_lines', models.JSONField(default=list)),
                ('service_type', models.TextField(default='installation')),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['job_id'], name='jobs_jobcom_job_id_2187ef_idx'), models.Index(fields=['email'], name='jobs_jobcom_email_919b0a_idx'), models.Index(fields=['phone'], name='jobs_jobcom_phone_6a5a34_idx'), models.Index(fields=['-completed_at'], name='jobs_jobcom_complet_357585_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_products', to='jobs.job')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='job_products', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['job'], name='jobs_jobpro_job_id_bc7820_idx'), models.Index(fields=['product'], name='jobs_jobpro_product_8f003a_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_staff', to='jobs.job')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_staff', to='staff.staff')),
            ],
            options={
                'indexes': [models.Index(fields=['staff'], name='jobs_jobsta_staff_i_22eaf6_idx'), models.Index(fields=['job'], name='jobs_jobsta_job_id_18abe6_idx')],
                'unique_together': {('job', 'staff')},
            },
        ),
    ]
