# Generated by Django 5.1.4 on 2026-06-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='import_contact_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['import_contact_id'], name='jobs_job_import__b125fe_idx'),
        ),
    ]
