# Generated by Django 5.1.4 on 2026-06-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_import_contact_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobcompletion',
            name='email',
            field=models.TextField(blank=True),
        ),
    ]
