# Generated by Django 5.1.4 on 2026-06-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_email_alter_jobcompletion_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
