# Generated by Django 5.1.4 on 2026-06-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.IntegerField(default=60),
        ),
    ]
