# Generated by Django 5.1.4 on 2026-06-26 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='occurrence_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='parent_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_jobs', to='jobs.job'),
        ),
    ]
