# Generated by Django 5.1.4 on 2026-06-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_occurrence_index_job_parent_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='color',
        ),
    ]
