# Generated by Django 5.1.4 on 2026-06-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_job_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('skip', 'Skip'), ('not_interested', 'Not Interested'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20),
        ),
    ]
