# Generated by Django 5.1.4 on 2026-06-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='total_occurrences',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
