# Generated by Django 5.1.4 on 2026-06-29 19:37

from django.db import migrations, models


def backfill_total_occurrences(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    Job.objects.all().update(total_occurrences=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_total_occurrences'),
    ]

    operations = [
        migrations.RunPython(backfill_total_occurrences, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='job',
            name='total_occurrences',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
