# Generated by Django 5.1.4 on 2026-08-07 15:30

from django.db import migrations, models


def backfill_completed_at(apps, schema_editor):
    """One-time backfill: use created_at as the best available proxy for
    completion time on jobs that already existed before this field. New jobs
    created after this migration keep completed_at = null unless explicitly
    supplied (e.g. via the migrate-job page)."""
    Job = apps.get_model('jobs', 'Job')
    Job.objects.filter(completed_at__isnull=True).update(completed_at=models.F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_total_occurrences_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_completed_at, migrations.RunPython.noop),
    ]
