# Generated by Django 5.1.4 on 2026-08-13 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_completed_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobCompletion',
        ),
    ]
