# Generated by Django 5.1.4 on 2026-08-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_jobcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment_status',
            field=models.CharField(
                choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')],
                default='paid',
                max_length=20,
            ),
        ),
    ]
