# Generated by Django 5.1.4 on 2026-08-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
