# Generated by Django 5.1.4 on 2026-08-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
    ]
