# Generated by Django 5.1.4 on 2026-08-27 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('jobs', '0015_job_is_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='activities.activity'),
        ),
    ]
