# Generated by Django 5.1.4 on 2026-09-01 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_job_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, choices=[('connected', 'Connected'), ('not_connected', 'Not connected'), ('call_back', 'Call back'), ('no_answer', 'No answer')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='jobs.job')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['job'], name='jobs_jobcal_job_id_44c359_idx')],
            },
        ),
    ]
