# Generated by Django 5.1.4 on 2026-09-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_jobcall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='service_type',
            field=models.TextField(choices=[('installation', 'Installation'), ('servicing', 'Servicing'), ('ad_hoc', 'Ad-hoc')], default='servicing'),
        ),
    ]
