# Generated by Django 5.1.4 on 2026-09-21 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_alter_job_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='service_type',
            field=models.TextField(choices=[('installation', 'Installation'), ('servicing', 'Servicing'), ('ad_hoc', 'Ad-hoc'), ('workshop', 'Workshop')], default='servicing'),
        ),
        migrations.CreateModel(
            name='JobAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('name', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job'], name='jobs_jobatt_job_id_a18aca_idx')],
            },
        ),
    ]
