# Generated by Django 5.1.4 on 2026-06-09 13:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('plan_date', models.DateField()),
                ('base_id', models.UUIDField(blank=True, null=True)),
                ('base_name', models.TextField(blank=True, null=True)),
                ('route_shape', models.TextField(default='round')),
                ('optimize_metric', models.TextField(default='time')),
                ('ordered_job_ids', models.JSONField(default=list)),
                ('staff_ids', models.JSONField(default=list)),
                ('road_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('road_minutes', models.IntegerField(blank=True, null=True)),
                ('legs', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-plan_date', '-created_at'],
                'indexes': [models.Index(fields=['plan_date'], name='plans_saved_plan_da_35ec0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.UUIDField()),
                ('staff_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('en_route', 'En Route'), ('on_site', 'On Site'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('issue', 'Issue')], default='pending', max_length=20)),
                ('actual_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='plans.savedplan')),
            ],
            options={
                'indexes': [models.Index(fields=['plan'], name='plans_jobpr_plan_id_144456_idx'), models.Index(fields=['job_id'], name='plans_jobpr_job_id_a22edb_idx'), models.Index(fields=['staff_id'], name='plans_jobpr_staff_i_aaa08b_idx')],
                'unique_together': {('plan', 'job_id', 'staff_id')},
            },
        ),
    ]
