# Generated by Django 5.1.4 on 2026-06-09 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhlToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(default='')),
                ('expires_at', models.DateTimeField()),
                ('location_id', models.TextField(blank=True, null=True)),
                ('company_id', models.TextField(blank=True, null=True)),
                ('user_type', models.TextField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('location_id__isnull', False)), fields=('location_id',), name='ghl_tokens_location_unique')],
            },
        ),
        migrations.CreateModel(
            name='GhlWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('type', models.TextField(blank=True, null=True)),
                ('entity_id', models.TextField(blank=True, null=True)),
                ('entity_table', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='ghl_ghlwebh_created_005e8a_idx'), models.Index(fields=['status'], name='ghl_ghlwebh_status_c74057_idx'), models.Index(fields=['entity_id'], name='ghl_ghlwebh_entity__760ffd_idx')],
            },
        ),
    ]
